//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Pelicula.java
//  @ Date : 29/11/2021
//  @ Author : 
//
//




public class Pelicula {
	public Object idPelicula;
	public Object nombre;
	public Object director;
	public Object genero;
	public Object anio;
	public Object clasificacion;
	public Object resena;
	public Object estreno;
	public Object costo;
}
