//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : renta.java
//  @ Date : 29/11/2021
//  @ Author : 
//
//




public class renta {
	public Object idRenta;
	public Object idCliente;
	public Object idSucursal;
	public Object idPelicula;
}
