//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : socio.java
//  @ Date : 29/11/2021
//  @ Author : 
//
//




public class socio {
	public Object idSocio;
	public Object nombre;
	public Object correo;
	public Object password;
	public Object direccion;
	public Object edad;
}
