//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : sucursal.java
//  @ Date : 29/11/2021
//  @ Author : 
//
//




public class sucursal {
	public Object idSucursal;
	public Object direccion;
	public Object telefono;
	public Object horario;
	public Object imagen;
}
